/*
Code generated by dmrgen.
DO NOT EDIT.
*/

package vocoder

import (
	bit "github.com/USA-RedDragon/dmrgo/dmr/bit"
	fec "github.com/USA-RedDragon/dmrgo/dmr/fec"
)

func DecodeVocoderFrame(data [72]bit.Bit) (VocoderFrame, fec.FECResult) {
	var result VocoderFrame
	_decoded, fecResult := decodeAMBE(data)
	result.DecodedBits = _decoded
	result.FEC = fecResult
	return result, fecResult
}

func EncodeVocoderFrame(s *VocoderFrame) [72]bit.Bit {
	return encodeAMBE(s.DecodedBits)
}
