// Code generated by dmrgen. DO NOT EDIT.

package pdu

import (
	bit "github.com/USA-RedDragon/dmrgo/dmr/bit"
	fec "github.com/USA-RedDragon/dmrgo/dmr/fec"
)

func DecodeBSOutboundActivationPDU(data [64]bit.Bit) (BSOutboundActivationPDU, fec.FECResult) {
	var result BSOutboundActivationPDU
	var fecResult fec.FECResult
	result.Reserved = bit.BitsToUint16(data[:], 0, 16)
	copy(result.BSAddress[:], data[16:40])
	copy(result.SourceAddress[:], data[40:64])
	return result, fecResult
}

func EncodeBSOutboundActivationPDU(s *BSOutboundActivationPDU) [64]bit.Bit {
	var data [64]bit.Bit
	copy(data[0:16], bit.BitsFromUint16(s.Reserved, 16))
	copy(data[16:40], s.BSAddress[:])
	copy(data[40:64], s.SourceAddress[:])
	return data
}
func DecodeUnitToUnitVoiceServiceRequestPDU(data [64]bit.Bit) (UnitToUnitVoiceServiceRequestPDU, fec.FECResult) {
	var result UnitToUnitVoiceServiceRequestPDU
	var fecResult fec.FECResult
	result.ServiceOptions = bit.BitsToUint8(data[:], 0, 8)
	result.Reserved = bit.BitsToUint8(data[:], 8, 8)
	copy(result.TargetAddress[:], data[16:40])
	copy(result.SourceAddress[:], data[40:64])
	return result, fecResult
}

func EncodeUnitToUnitVoiceServiceRequestPDU(s *UnitToUnitVoiceServiceRequestPDU) [64]bit.Bit {
	var data [64]bit.Bit
	copy(data[0:8], bit.BitsFromUint8(uint8(s.ServiceOptions), 8))
	copy(data[8:16], bit.BitsFromUint8(uint8(s.Reserved), 8))
	copy(data[16:40], s.TargetAddress[:])
	copy(data[40:64], s.SourceAddress[:])
	return data
}
func DecodeUnitToUnitVoiceServiceAnswerResponsePDU(data [64]bit.Bit) (UnitToUnitVoiceServiceAnswerResponsePDU, fec.FECResult) {
	var result UnitToUnitVoiceServiceAnswerResponsePDU
	var fecResult fec.FECResult
	result.ServiceOptions = bit.BitsToUint8(data[:], 0, 8)
	result.AnswerResponse = bit.BitsToUint8(data[:], 8, 8)
	copy(result.TargetAddress[:], data[16:40])
	copy(result.SourceAddress[:], data[40:64])
	return result, fecResult
}

func EncodeUnitToUnitVoiceServiceAnswerResponsePDU(s *UnitToUnitVoiceServiceAnswerResponsePDU) [64]bit.Bit {
	var data [64]bit.Bit
	copy(data[0:8], bit.BitsFromUint8(uint8(s.ServiceOptions), 8))
	copy(data[8:16], bit.BitsFromUint8(uint8(s.AnswerResponse), 8))
	copy(data[16:40], s.TargetAddress[:])
	copy(data[40:64], s.SourceAddress[:])
	return data
}
func DecodeNegativeAcknowledgementPDU(data [64]bit.Bit) (NegativeAcknowledgementPDU, fec.FECResult) {
	var result NegativeAcknowledgementPDU
	var fecResult fec.FECResult
	result.AdditionalInfo = bit.BitsToBool(data[:], 0)
	result.SourceType = bit.BitsToBool(data[:], 1)
	copy(result.ServiceType[:], data[2:8])
	result.ReasonCode = bit.BitsToUint8(data[:], 8, 8)
	copy(result.SourceAddress[:], data[16:40])
	copy(result.TargetAddress[:], data[40:64])
	return result, fecResult
}

func EncodeNegativeAcknowledgementPDU(s *NegativeAcknowledgementPDU) [64]bit.Bit {
	var data [64]bit.Bit
	if s.AdditionalInfo {
		data[0] = 1
	}
	if s.SourceType {
		data[1] = 1
	}
	copy(data[2:8], s.ServiceType[:])
	copy(data[8:16], bit.BitsFromUint8(uint8(s.ReasonCode), 8))
	copy(data[16:40], s.SourceAddress[:])
	copy(data[40:64], s.TargetAddress[:])
	return data
}
func DecodePreamblePDU(data [64]bit.Bit) (PreamblePDU, fec.FECResult) {
	var result PreamblePDU
	var fecResult fec.FECResult
	result.Data = bit.BitsToBool(data[:], 0)
	result.Group = bit.BitsToBool(data[:], 1)
	copy(result.Reserved[:], data[2:8])
	result.CSBKBlocksToFollow = bit.BitsToUint8(data[:], 8, 8)
	copy(result.TargetAddress[:], data[16:40])
	copy(result.SourceAddress[:], data[40:64])
	return result, fecResult
}

func EncodePreamblePDU(s *PreamblePDU) [64]bit.Bit {
	var data [64]bit.Bit
	if s.Data {
		data[0] = 1
	}
	if s.Group {
		data[1] = 1
	}
	copy(data[2:8], s.Reserved[:])
	copy(data[8:16], bit.BitsFromUint8(uint8(s.CSBKBlocksToFollow), 8))
	copy(data[16:40], s.TargetAddress[:])
	copy(data[40:64], s.SourceAddress[:])
	return data
}
