// Code generated by dmrgen. DO NOT EDIT.

package pdu

import (
	bit "github.com/USA-RedDragon/dmrgo/dmr/bit"
	fec "github.com/USA-RedDragon/dmrgo/dmr/fec"
)

func DecodeUnconfirmedDataHeader(data [80]bit.Bit) (UnconfirmedDataHeader, fec.FECResult) {
	var result UnconfirmedDataHeader
	var fecResult fec.FECResult
	result.Group = bit.BitsToBool(data[:], 0)
	result.ResponseRequested = bit.BitsToBool(data[:], 1)
	result.Reserved = bit.BitsToBool(data[:], 2)
	var _tmpPadOctetCount uint8
	_tmpPadOctetCount = bit.BitsToUint8(data[:], 3, 1)
	_tmpPadOctetCount <<= 4
	_tmpPadOctetCount |= bit.BitsToUint8(data[:], 12, 4)
	result.PadOctetCount = _tmpPadOctetCount
	copy(result.LLIDDestination[:], data[16:40])
	copy(result.LLIDSource[:], data[40:64])
	result.FullMessage = bit.BitsToBool(data[:], 64)
	result.BlocksToFollow = bit.BitsToUint8(data[:], 65, 7)
	copy(result.Reserved2[:], data[72:76])
	result.FragmentSequenceNumber = bit.BitsToUint8(data[:], 76, 4)
	return result, fecResult
}

func EncodeUnconfirmedDataHeader(s *UnconfirmedDataHeader) [80]bit.Bit {
	var data [80]bit.Bit
	if s.Group {
		data[0] = 1
	}
	if s.ResponseRequested {
		data[1] = 1
	}
	if s.Reserved {
		data[2] = 1
	}
	copy(data[3:4], bit.BitsFromUint8((uint8(s.PadOctetCount))>>4, 1))
	copy(data[12:16], bit.BitsFromUint8(s.PadOctetCount, 4))
	copy(data[16:40], s.LLIDDestination[:])
	copy(data[40:64], s.LLIDSource[:])
	if s.FullMessage {
		data[64] = 1
	}
	copy(data[65:72], bit.BitsFromUint8(s.BlocksToFollow, 7))
	copy(data[72:76], s.Reserved2[:])
	copy(data[76:80], bit.BitsFromUint8(s.FragmentSequenceNumber, 4))
	return data
}
