// Code generated by dmrgen. DO NOT EDIT.

package pdu

import (
	bit "github.com/USA-RedDragon/dmrgo/dmr/bit"
	enums "github.com/USA-RedDragon/dmrgo/dmr/enums"
	fec "github.com/USA-RedDragon/dmrgo/dmr/fec"
	"github.com/USA-RedDragon/dmrgo/dmr/fec/quadratic_residue"
)

func DecodeEmbeddedSignalling(data [16]bit.Bit) (EmbeddedSignalling, fec.FECResult) {
	var result EmbeddedSignalling
	corrected, fecResult := quadratic_residue.Decode(data)
	result.FEC = fecResult
	if !fecResult.Uncorrectable {
		data = corrected
	}
	result.ColorCode = bit.BitsToInt(data[:], 0, 4)
	result.PreemptionAndPowerControlIndicator = bit.BitsToBool(data[:], 4)
	result.LCSS = enums.LCSSFromInt(bit.BitsToInt(data[:], 5, 2))
	return result, fecResult
}

func EncodeEmbeddedSignalling(s *EmbeddedSignalling) [16]bit.Bit {
	var data [7]bit.Bit
	copy(data[0:4], bit.BitsFromUint32(uint32(s.ColorCode), 4))
	if s.PreemptionAndPowerControlIndicator {
		data[4] = 1
	}
	copy(data[5:7], bit.BitsFromUint8(uint8(s.LCSS), 2))
	return quadratic_residue.Encode(bit.BitsToValue(data[:]))
}
