/*
Code generated by dmrgen.

ETSI TS 102 361-1 V2.5.1 (2017-10) - 9.1.7 Rate 1 data

DO NOT EDIT.
*/

package pdu

import (
	"fmt"
	bit "github.com/USA-RedDragon/dmrgo/dmr/bit"
	fec "github.com/USA-RedDragon/dmrgo/dmr/fec"
	layer2Elements "github.com/USA-RedDragon/dmrgo/dmr/layer2/elements"
)

// DecodeRate1Data decodes a Rate1Data per ETSI TS 102 361-1 V2.5.1 (2017-10) - 9.1.7 Rate 1 data
func DecodeRate1Data(data [96]bit.Bit) (Rate1Data, fec.FECResult) {
	var result Rate1Data
	var fecResult fec.FECResult
	copy(result.Data[:], bit.PackBits(data[0:96]))
	return result, fecResult
}

// EncodeRate1Data encodes a Rate1Data per ETSI TS 102 361-1 V2.5.1 (2017-10) - 9.1.7 Rate 1 data
func EncodeRate1Data(s *Rate1Data) [96]bit.Bit {
	var data [96]bit.Bit
	copy(data[0:96], bit.UnpackBits(s.Data[:]))
	return data
}

func (s *Rate1Data) ToString() string {
	return fmt.Sprintf("Rate1Data{ DataType: %s, Data: %v }", layer2Elements.DataTypeToName(s.DataType), s.Data)
}
