// Code generated by dmrgen. DO NOT EDIT.

package pdu

import (
	bit "github.com/USA-RedDragon/dmrgo/dmr/bit"
	fec "github.com/USA-RedDragon/dmrgo/dmr/fec"
)

func DecodeRate34Data(data [96]bit.Bit) (Rate34Data, fec.FECResult) {
	var result Rate34Data
	var fecResult fec.FECResult
	copy(result.Data[:], bit.PackBits(data[0:96]))
	return result, fecResult
}

func EncodeRate34Data(s *Rate34Data) [96]bit.Bit {
	var data [96]bit.Bit
	copy(data[0:96], bit.UnpackBits(s.Data[:]))
	return data
}
