/*
Code generated by dmrgen.

ETSI TS 102 361-1 V2.5.1 (2017-10) - 9.1.7 Rate 1/2 data

DO NOT EDIT.
*/

package pdu

import (
	bit "github.com/USA-RedDragon/dmrgo/dmr/bit"
	fec "github.com/USA-RedDragon/dmrgo/dmr/fec"
)

// DecodeRate12Data decodes a Rate12Data per ETSI TS 102 361-1 V2.5.1 (2017-10) - 9.1.7 Rate 1/2 data
func DecodeRate12Data(data [96]bit.Bit) (Rate12Data, fec.FECResult) {
	var result Rate12Data
	var fecResult fec.FECResult
	copy(result.Data[:], bit.PackBits(data[0:96]))
	return result, fecResult
}

// EncodeRate12Data encodes a Rate12Data per ETSI TS 102 361-1 V2.5.1 (2017-10) - 9.1.7 Rate 1/2 data
func EncodeRate12Data(s *Rate12Data) [96]bit.Bit {
	var data [96]bit.Bit
	copy(data[0:96], bit.UnpackBits(s.Data[:]))
	return data
}
