/*
Code generated by dmrgen.

ETSI TS 102 361-1 V2.5.1 (2017-10) - 7.1 Voice channel coding

DO NOT EDIT.
*/

package pdu

import (
	bit "github.com/USA-RedDragon/dmrgo/dmr/bit"
	fec "github.com/USA-RedDragon/dmrgo/dmr/fec"
	vocoder "github.com/USA-RedDragon/dmrgo/dmr/vocoder"
)

// DecodeVocoder decodes a Vocoder per ETSI TS 102 361-1 V2.5.1 (2017-10) - 7.1 Voice channel coding
func DecodeVocoder(data [216]bit.Bit) (Vocoder, fec.FECResult) {
	var result Vocoder
	var fecResult fec.FECResult
	for _i := 0; _i < 3; _i++ {
		var _elemBits [72]bit.Bit
		copy(_elemBits[:], data[0+_i*72:0+_i*72+72])
		result.Frames[_i] = vocoder.NewVocoderFrameFromBits(_elemBits)
	}
	return result, fecResult
}

// EncodeVocoder encodes a Vocoder per ETSI TS 102 361-1 V2.5.1 (2017-10) - 7.1 Voice channel coding
func EncodeVocoder(s *Vocoder) [216]bit.Bit {
	var data [216]bit.Bit
	for _i := 0; _i < 3; _i++ {
		_elemBits := s.Frames[_i].Encode()
		copy(data[0+_i*72:0+_i*72+72], _elemBits[:])
	}
	return data
}
