/*
Code generated by dmrgen.

ETSI TS 102 361-1 - 9.3.6 BS Outbound Activation (BS_Dwn_Act) PDU
ETSI TS 102 361-1 - 9.3.2 UU_V_Req PDU
ETSI TS 102 361-1 - 9.3.3 UU_Ans_Rsp PDU
ETSI TS 102 361-1 - 9.3.5 NACK_Rsp PDU
ETSI TS 102 361-1 - 9.3.7 Pre PDU
ETSI TS 102 361-1 - 9.3.8 Ch_Timing (Channel Timing) PDU
ETSI TS 102 361-1 - 9.1.5 CSBK PDU

DO NOT EDIT.
*/

package pdu

import (
	"fmt"
	bit "github.com/USA-RedDragon/dmrgo/v2/bit"
	crc "github.com/USA-RedDragon/dmrgo/v2/crc"
	fec "github.com/USA-RedDragon/dmrgo/v2/fec"
	layer2Elements "github.com/USA-RedDragon/dmrgo/v2/layer2/elements"
)

// DecodeBSOutboundActivationPDU decodes a BSOutboundActivationPDU per ETSI TS 102 361-1 - 9.3.6 BS Outbound Activation (BS_Dwn_Act) PDU
func DecodeBSOutboundActivationPDU(data [64]bit.Bit) (BSOutboundActivationPDU, fec.FECResult) {
	var result BSOutboundActivationPDU
	var fecResult fec.FECResult
	result.Reserved = bit.BitsToUint16(data[:], 0, 16)
	copy(result.BSAddress[:], data[16:40])
	copy(result.SourceAddress[:], data[40:64])
	return result, fecResult
}

// EncodeBSOutboundActivationPDU encodes a BSOutboundActivationPDU per ETSI TS 102 361-1 - 9.3.6 BS Outbound Activation (BS_Dwn_Act) PDU
func EncodeBSOutboundActivationPDU(s *BSOutboundActivationPDU) [64]bit.Bit {
	var data [64]bit.Bit
	copy(data[0:16], bit.BitsFromUint16(s.Reserved, 16))
	copy(data[16:40], s.BSAddress[:])
	copy(data[40:64], s.SourceAddress[:])
	return data
}

func (s *BSOutboundActivationPDU) ToString() string {
	return fmt.Sprintf("BSOutboundActivationPDU{ Reserved: %d, BSAddress: %v, SourceAddress: %v }", s.Reserved, s.BSAddress, s.SourceAddress)
}

// DecodeUnitToUnitVoiceServiceRequestPDU decodes a UnitToUnitVoiceServiceRequestPDU per ETSI TS 102 361-1 - 9.3.2 UU_V_Req PDU
func DecodeUnitToUnitVoiceServiceRequestPDU(data [64]bit.Bit) (UnitToUnitVoiceServiceRequestPDU, fec.FECResult) {
	var result UnitToUnitVoiceServiceRequestPDU
	var fecResult fec.FECResult
	result.ServiceOptions = bit.BitsToUint8(data[:], 0, 8)
	result.Reserved = bit.BitsToUint8(data[:], 8, 8)
	copy(result.TargetAddress[:], data[16:40])
	copy(result.SourceAddress[:], data[40:64])
	return result, fecResult
}

// EncodeUnitToUnitVoiceServiceRequestPDU encodes a UnitToUnitVoiceServiceRequestPDU per ETSI TS 102 361-1 - 9.3.2 UU_V_Req PDU
func EncodeUnitToUnitVoiceServiceRequestPDU(s *UnitToUnitVoiceServiceRequestPDU) [64]bit.Bit {
	var data [64]bit.Bit
	copy(data[0:8], bit.BitsFromUint8(uint8(s.ServiceOptions), 8))
	copy(data[8:16], bit.BitsFromUint8(uint8(s.Reserved), 8))
	copy(data[16:40], s.TargetAddress[:])
	copy(data[40:64], s.SourceAddress[:])
	return data
}

func (s *UnitToUnitVoiceServiceRequestPDU) ToString() string {
	return fmt.Sprintf("UnitToUnitVoiceServiceRequestPDU{ ServiceOptions: %d, Reserved: %d, TargetAddress: %v, SourceAddress: %v }", s.ServiceOptions, s.Reserved, s.TargetAddress, s.SourceAddress)
}

// DecodeUnitToUnitVoiceServiceAnswerResponsePDU decodes a UnitToUnitVoiceServiceAnswerResponsePDU per ETSI TS 102 361-1 - 9.3.3 UU_Ans_Rsp PDU
func DecodeUnitToUnitVoiceServiceAnswerResponsePDU(data [64]bit.Bit) (UnitToUnitVoiceServiceAnswerResponsePDU, fec.FECResult) {
	var result UnitToUnitVoiceServiceAnswerResponsePDU
	var fecResult fec.FECResult
	result.ServiceOptions = bit.BitsToUint8(data[:], 0, 8)
	result.AnswerResponse = bit.BitsToUint8(data[:], 8, 8)
	copy(result.TargetAddress[:], data[16:40])
	copy(result.SourceAddress[:], data[40:64])
	return result, fecResult
}

// EncodeUnitToUnitVoiceServiceAnswerResponsePDU encodes a UnitToUnitVoiceServiceAnswerResponsePDU per ETSI TS 102 361-1 - 9.3.3 UU_Ans_Rsp PDU
func EncodeUnitToUnitVoiceServiceAnswerResponsePDU(s *UnitToUnitVoiceServiceAnswerResponsePDU) [64]bit.Bit {
	var data [64]bit.Bit
	copy(data[0:8], bit.BitsFromUint8(uint8(s.ServiceOptions), 8))
	copy(data[8:16], bit.BitsFromUint8(uint8(s.AnswerResponse), 8))
	copy(data[16:40], s.TargetAddress[:])
	copy(data[40:64], s.SourceAddress[:])
	return data
}

func (s *UnitToUnitVoiceServiceAnswerResponsePDU) ToString() string {
	return fmt.Sprintf("UnitToUnitVoiceServiceAnswerResponsePDU{ ServiceOptions: %d, AnswerResponse: %d, TargetAddress: %v, SourceAddress: %v }", s.ServiceOptions, s.AnswerResponse, s.TargetAddress, s.SourceAddress)
}

// DecodeNegativeAcknowledgementPDU decodes a NegativeAcknowledgementPDU per ETSI TS 102 361-1 - 9.3.5 NACK_Rsp PDU
func DecodeNegativeAcknowledgementPDU(data [64]bit.Bit) (NegativeAcknowledgementPDU, fec.FECResult) {
	var result NegativeAcknowledgementPDU
	var fecResult fec.FECResult
	result.AdditionalInfo = bit.BitsToBool(data[:], 0)
	result.SourceType = bit.BitsToBool(data[:], 1)
	copy(result.ServiceType[:], data[2:8])
	result.ReasonCode = bit.BitsToUint8(data[:], 8, 8)
	copy(result.SourceAddress[:], data[16:40])
	copy(result.TargetAddress[:], data[40:64])
	return result, fecResult
}

// EncodeNegativeAcknowledgementPDU encodes a NegativeAcknowledgementPDU per ETSI TS 102 361-1 - 9.3.5 NACK_Rsp PDU
func EncodeNegativeAcknowledgementPDU(s *NegativeAcknowledgementPDU) [64]bit.Bit {
	var data [64]bit.Bit
	if s.AdditionalInfo {
		data[0] = 1
	}
	if s.SourceType {
		data[1] = 1
	}
	copy(data[2:8], s.ServiceType[:])
	copy(data[8:16], bit.BitsFromUint8(uint8(s.ReasonCode), 8))
	copy(data[16:40], s.SourceAddress[:])
	copy(data[40:64], s.TargetAddress[:])
	return data
}

func (s *NegativeAcknowledgementPDU) ToString() string {
	return fmt.Sprintf("NegativeAcknowledgementPDU{ AdditionalInfo: %t, SourceType: %t, ServiceType: %v, ReasonCode: %d, SourceAddress: %v, TargetAddress: %v }", s.AdditionalInfo, s.SourceType, s.ServiceType, s.ReasonCode, s.SourceAddress, s.TargetAddress)
}

// DecodePreamblePDU decodes a PreamblePDU per ETSI TS 102 361-1 - 9.3.7 Pre PDU
func DecodePreamblePDU(data [64]bit.Bit) (PreamblePDU, fec.FECResult) {
	var result PreamblePDU
	var fecResult fec.FECResult
	result.Data = bit.BitsToBool(data[:], 0)
	result.Group = bit.BitsToBool(data[:], 1)
	copy(result.Reserved[:], data[2:8])
	result.CSBKBlocksToFollow = bit.BitsToUint8(data[:], 8, 8)
	copy(result.TargetAddress[:], data[16:40])
	copy(result.SourceAddress[:], data[40:64])
	return result, fecResult
}

// EncodePreamblePDU encodes a PreamblePDU per ETSI TS 102 361-1 - 9.3.7 Pre PDU
func EncodePreamblePDU(s *PreamblePDU) [64]bit.Bit {
	var data [64]bit.Bit
	if s.Data {
		data[0] = 1
	}
	if s.Group {
		data[1] = 1
	}
	copy(data[2:8], s.Reserved[:])
	copy(data[8:16], bit.BitsFromUint8(uint8(s.CSBKBlocksToFollow), 8))
	copy(data[16:40], s.TargetAddress[:])
	copy(data[40:64], s.SourceAddress[:])
	return data
}

func (s *PreamblePDU) ToString() string {
	return fmt.Sprintf("PreamblePDU{ Data: %t, Group: %t, Reserved: %v, CSBKBlocksToFollow: %d, TargetAddress: %v, SourceAddress: %v }", s.Data, s.Group, s.Reserved, s.CSBKBlocksToFollow, s.TargetAddress, s.SourceAddress)
}

// DecodeChannelTimingPDU decodes a ChannelTimingPDU per ETSI TS 102 361-1 - 9.3.8 Ch_Timing (Channel Timing) PDU
func DecodeChannelTimingPDU(data [64]bit.Bit) (ChannelTimingPDU, fec.FECResult) {
	var result ChannelTimingPDU
	var fecResult fec.FECResult
	copy(result.SyncAge[:], data[0:11])
	copy(result.Generation[:], data[11:16])
	copy(result.LeaderIdentifier[:], data[16:36])
	result.NewLeader = bit.BitsToBool(data[:], 36)
	copy(result.LeaderDynamicIdentifier[:], data[37:39])
	result.ChannelTimingOp0 = bit.BitsToBool(data[:], 39)
	copy(result.SourceIdentifier[:], data[40:60])
	result.Reserved = bit.BitsToBool(data[:], 60)
	copy(result.SourceDynamicIdentifier[:], data[61:63])
	result.ChannelTimingOp1 = bit.BitsToBool(data[:], 63)
	return result, fecResult
}

// EncodeChannelTimingPDU encodes a ChannelTimingPDU per ETSI TS 102 361-1 - 9.3.8 Ch_Timing (Channel Timing) PDU
func EncodeChannelTimingPDU(s *ChannelTimingPDU) [64]bit.Bit {
	var data [64]bit.Bit
	copy(data[0:11], s.SyncAge[:])
	copy(data[11:16], s.Generation[:])
	copy(data[16:36], s.LeaderIdentifier[:])
	if s.NewLeader {
		data[36] = 1
	}
	copy(data[37:39], s.LeaderDynamicIdentifier[:])
	if s.ChannelTimingOp0 {
		data[39] = 1
	}
	copy(data[40:60], s.SourceIdentifier[:])
	if s.Reserved {
		data[60] = 1
	}
	copy(data[61:63], s.SourceDynamicIdentifier[:])
	if s.ChannelTimingOp1 {
		data[63] = 1
	}
	return data
}

func (s *ChannelTimingPDU) ToString() string {
	return fmt.Sprintf("ChannelTimingPDU{ SyncAge: %v, Generation: %v, LeaderIdentifier: %v, NewLeader: %t, LeaderDynamicIdentifier: %v, ChannelTimingOp0: %t, SourceIdentifier: %v, Reserved: %t, SourceDynamicIdentifier: %v, ChannelTimingOp1: %t }", s.SyncAge, s.Generation, s.LeaderIdentifier, s.NewLeader, s.LeaderDynamicIdentifier, s.ChannelTimingOp0, s.SourceIdentifier, s.Reserved, s.SourceDynamicIdentifier, s.ChannelTimingOp1)
}

// DecodeCSBK decodes a CSBK per ETSI TS 102 361-1 - 9.1.5 CSBK PDU
func DecodeCSBK(data [96]bit.Bit) (CSBK, fec.FECResult) {
	var result CSBK
	var _packedBytes [12]byte
	for i := range 12 {
		for j := range 8 {
			_packedBytes[i] <<= 1
			_packedBytes[i] |= byte(data[i*8+j])
		}
	}
	_packedBytes[10] ^= uint8(0xa5)
	_packedBytes[11] ^= uint8(0xa5)
	var fecResult fec.FECResult
	fecResult.BitsChecked = 96
	if !crc.CheckCRCCCITT(_packedBytes[:]) {
		fecResult.Uncorrectable = true
	}
	result.FEC = fecResult
	result.crc = uint16(_packedBytes[10])<<8 | uint16(_packedBytes[11])
	result.LastBlock = bit.BitsToBool(data[:], 0)
	result.ProtectFlag = bit.BitsToBool(data[:], 1)
	result.CSBKOpcode = CSBKOpcode(bit.BitsToUint8(data[:], 2, 6))
	result.FID = bit.BitsToUint8(data[:], 8, 8)
	var _dispatchBits [64]bit.Bit
	copy(_dispatchBits[:], data[16:80])
	switch result.CSBKOpcode {
	case CSBKBSOutboundActivationPDU:
		_decoded, _ := DecodeBSOutboundActivationPDU(_dispatchBits)
		result.BSOutboundActivationPDU = &_decoded
	case CSBKUnitToUnitVoiceServiceRequestPDU:
		_decoded, _ := DecodeUnitToUnitVoiceServiceRequestPDU(_dispatchBits)
		result.UnitToUnitVoiceServiceRequestPDU = &_decoded
	case CSBKUnitToUnitVoiceServiceAnswerResponsePDU:
		_decoded, _ := DecodeUnitToUnitVoiceServiceAnswerResponsePDU(_dispatchBits)
		result.UnitToUnitVoiceServiceAnswerResponsePDU = &_decoded
	case CSBKNegativeAcknowledgementPDU:
		_decoded, _ := DecodeNegativeAcknowledgementPDU(_dispatchBits)
		result.NegativeAcknowledgementPDU = &_decoded
	case CSBKPreamblePDU:
		_decoded, _ := DecodePreamblePDU(_dispatchBits)
		result.PreamblePDU = &_decoded
	case CSBKChannelTimingPDU:
		_decoded, _ := DecodeChannelTimingPDU(_dispatchBits)
		result.ChannelTimingPDU = &_decoded
	}
	return result, fecResult
}

// EncodeCSBK encodes a CSBK per ETSI TS 102 361-1 - 9.1.5 CSBK PDU
func EncodeCSBK(s *CSBK) [96]bit.Bit {
	var data [96]bit.Bit
	if s.LastBlock {
		data[0] = 1
	}
	if s.ProtectFlag {
		data[1] = 1
	}
	copy(data[2:8], bit.BitsFromUint8(uint8(s.CSBKOpcode), 6))
	copy(data[8:16], bit.BitsFromUint8(uint8(s.FID), 8))
	switch {
	case s.BSOutboundActivationPDU != nil:
		_pduBits := EncodeBSOutboundActivationPDU(s.BSOutboundActivationPDU)
		copy(data[16:80], _pduBits[:])
	case s.UnitToUnitVoiceServiceRequestPDU != nil:
		_pduBits := EncodeUnitToUnitVoiceServiceRequestPDU(s.UnitToUnitVoiceServiceRequestPDU)
		copy(data[16:80], _pduBits[:])
	case s.UnitToUnitVoiceServiceAnswerResponsePDU != nil:
		_pduBits := EncodeUnitToUnitVoiceServiceAnswerResponsePDU(s.UnitToUnitVoiceServiceAnswerResponsePDU)
		copy(data[16:80], _pduBits[:])
	case s.NegativeAcknowledgementPDU != nil:
		_pduBits := EncodeNegativeAcknowledgementPDU(s.NegativeAcknowledgementPDU)
		copy(data[16:80], _pduBits[:])
	case s.PreamblePDU != nil:
		_pduBits := EncodePreamblePDU(s.PreamblePDU)
		copy(data[16:80], _pduBits[:])
	case s.ChannelTimingPDU != nil:
		_pduBits := EncodeChannelTimingPDU(s.ChannelTimingPDU)
		copy(data[16:80], _pduBits[:])
	}
	var _encBytes [10]byte
	for i := range 10 {
		for j := range 8 {
			_encBytes[i] <<= 1
			_encBytes[i] |= byte(data[i*8+j])
		}
	}
	_crcVal := crc.CalculateCRCCCITT(_encBytes[:])
	_crcHigh := byte(_crcVal >> 8)
	_crcLow := byte(_crcVal)
	_crcHigh ^= uint8(0xa5)
	_crcLow ^= uint8(0xa5)
	for j := range 8 {
		data[80+j] = bit.Bit((_crcHigh >> (7 - j)) & 1)
	}
	for j := range 8 {
		data[88+j] = bit.Bit((_crcLow >> (7 - j)) & 1)
	}
	return data
}

func (s *CSBK) ToString() string {
	_ret := "CSBK{ "
	_ret += fmt.Sprintf("DataType: %s, LastBlock: %t, ProtectFlag: %t, CSBKOpcode: %d, FID: %d, FEC: {BitsChecked: %d, ErrorsCorrected: %d, Uncorrectable: %t}, ", layer2Elements.DataTypeToName(s.DataType), s.LastBlock, s.ProtectFlag, s.CSBKOpcode, s.FID, s.FEC.BitsChecked, s.FEC.ErrorsCorrected, s.FEC.Uncorrectable)
	switch {
	case s.BSOutboundActivationPDU != nil:
		_ret += s.BSOutboundActivationPDU.ToString()
	case s.UnitToUnitVoiceServiceRequestPDU != nil:
		_ret += s.UnitToUnitVoiceServiceRequestPDU.ToString()
	case s.UnitToUnitVoiceServiceAnswerResponsePDU != nil:
		_ret += s.UnitToUnitVoiceServiceAnswerResponsePDU.ToString()
	case s.NegativeAcknowledgementPDU != nil:
		_ret += s.NegativeAcknowledgementPDU.ToString()
	case s.PreamblePDU != nil:
		_ret += s.PreamblePDU.ToString()
	case s.ChannelTimingPDU != nil:
		_ret += s.ChannelTimingPDU.ToString()
	}
	_ret += " }"
	return _ret
}
