/*
Code generated by dmrgen.

ETSI TS 102 361-1 - 9.1.2 Embedded signalling (EMB) PDU

DO NOT EDIT.
*/

package pdu

import (
	"fmt"
	bit "github.com/USA-RedDragon/dmrgo/v2/bit"
	enums "github.com/USA-RedDragon/dmrgo/v2/enums"
	fec "github.com/USA-RedDragon/dmrgo/v2/fec"
	"github.com/USA-RedDragon/dmrgo/v2/fec/quadratic_residue"
)

// DecodeEmbeddedSignalling decodes a EmbeddedSignalling per ETSI TS 102 361-1 - 9.1.2 Embedded signalling (EMB) PDU
func DecodeEmbeddedSignalling(data [16]bit.Bit) (EmbeddedSignalling, fec.FECResult) {
	var result EmbeddedSignalling
	corrected, fecResult := quadratic_residue.Decode(data)
	result.FEC = fecResult
	if !fecResult.Uncorrectable {
		data = corrected
	}
	result.ColorCode = bit.BitsToInt(data[:], 0, 4)
	result.PreemptionAndPowerControlIndicator = bit.BitsToBool(data[:], 4)
	result.LCSS = enums.LCSSFromInt(bit.BitsToInt(data[:], 5, 2))
	return result, fecResult
}

// EncodeEmbeddedSignalling encodes a EmbeddedSignalling per ETSI TS 102 361-1 - 9.1.2 Embedded signalling (EMB) PDU
func EncodeEmbeddedSignalling(s *EmbeddedSignalling) [16]bit.Bit {
	var data [7]bit.Bit
	copy(data[0:4], bit.BitsFromUint32(uint32(s.ColorCode), 4))
	if s.PreemptionAndPowerControlIndicator {
		data[4] = 1
	}
	copy(data[5:7], bit.BitsFromUint8(uint8(s.LCSS), 2))
	return quadratic_residue.Encode(bit.BitsToValue(data[:]))
}

func (s *EmbeddedSignalling) ToString() string {
	return fmt.Sprintf("EmbeddedSignalling{ ColorCode: %d, PreemptionAndPowerControlIndicator: %t, LCSS: %s, FEC: {BitsChecked: %d, ErrorsCorrected: %d, Uncorrectable: %t} }", s.ColorCode, s.PreemptionAndPowerControlIndicator, enums.LCSSToName(s.LCSS), s.FEC.BitsChecked, s.FEC.ErrorsCorrected, s.FEC.Uncorrectable)
}
