/*
Code generated by dmrgen.

ETSI TS 102 361-1 - 9.1.6  Full Link Control (FULL LC) PDU
ETSI TS 102 361-2 - Table 7.1: Grp_V_Ch_Usr PDU content
ETSI TS 102 361-2 - Table 7.2: UU_V_Ch_Usr PDU content
ETSI TS 102 361-2 - Table 7.3: GPS Info PDU content
ETSI TS 102 361-2 - Table 7.4: Talker Alias Header Info PDU content
ETSI TS 102 361-2 - Table 7.5: Talker Alias Blk PDU content
ETSI TS 102 361-3 - Table 7.1: Terminator Data Link Control PDU content

DO NOT EDIT.
*/

package pdu

import (
	"fmt"
	bit "github.com/USA-RedDragon/dmrgo/v2/bit"
	enums "github.com/USA-RedDragon/dmrgo/v2/enums"
	fec "github.com/USA-RedDragon/dmrgo/v2/fec"
	"github.com/USA-RedDragon/dmrgo/v2/fec/reed_solomon"
	layer2Elements "github.com/USA-RedDragon/dmrgo/v2/layer2/elements"
	layer3Elements "github.com/USA-RedDragon/dmrgo/v2/layer3/elements"
	"math"
)

// DecodeFullLinkControl decodes a FullLinkControl per ETSI TS 102 361-1 - 9.1.6  Full Link Control (FULL LC) PDU
func DecodeFullLinkControl(data [96]bit.Bit) (FullLinkControl, fec.FECResult) {
	var result FullLinkControl
	var _packedBytes [12]byte
	for i := range 12 {
		for j := range 8 {
			_packedBytes[i] <<= 1
			_packedBytes[i] |= byte(data[i*8+j])
		}
	}
	_rsResult := reedsolomon.Decode(_packedBytes[:])
	fecResult := fec.FECResult{
		BitsChecked:     96,
		ErrorsCorrected: _rsResult.ErrorsFound,
		Uncorrectable:   _rsResult.Uncorrectable,
	}
	result.FEC = fecResult
	if !_rsResult.Uncorrectable {
		for i := range 9 {
			for j := range 8 {
				data[i*8+j] = bit.Bit((_rsResult.Data[i] >> (7 - j)) & 1)
			}
		}
	}
	result.ProtectFlag = bit.BitsToBool(data[:], 0)
	{
		_enumVal, _ := enums.FLCOFromInt(bit.BitsToInt(data[:], 2, 6))
		result.FLCO = _enumVal
	}
	{
		_enumVal, _ := enums.FeatureSetIDFromInt(bit.BitsToInt(data[:], 8, 8))
		result.FeatureSetID = _enumVal
	}
	var _dispatchBits [56]bit.Bit
	copy(_dispatchBits[:], data[16:72])
	switch result.FLCO {
	case enums.FLCOGroupVoiceChannelUser:
		_decoded, _ := DecodeFLCGroupVoice(_dispatchBits)
		result.GroupVoice = &_decoded
	case enums.FLCOUnitToUnitVoiceChannelUser:
		_decoded, _ := DecodeFLCUnitToUnit(_dispatchBits)
		result.UnitToUnit = &_decoded
	case enums.FLCOGPSInfo:
		_decoded, _ := DecodeFLCGPSInfo(_dispatchBits)
		result.GPSInfo = &_decoded
	case enums.FLCOTalkerAliasHeader:
		_decoded, _ := DecodeFLCTalkerAliasHeader(_dispatchBits)
		result.TalkerAliasHeader = &_decoded
	case enums.FLCOTalkerAliasBlock1, enums.FLCOTalkerAliasBlock2, enums.FLCOTalkerAliasBlock3:
		_decoded, _ := DecodeFLCTalkerAliasBlock(_dispatchBits)
		result.TalkerAliasBlock = &_decoded
	case enums.FLCOTerminatorDataLinkControl:
		_decoded, _ := DecodeFLCTerminatorDataLinkControl(_dispatchBits)
		result.TerminatorDataLinkControl = &_decoded
	}
	return result, fecResult
}

// EncodeFullLinkControl encodes a FullLinkControl per ETSI TS 102 361-1 - 9.1.6  Full Link Control (FULL LC) PDU
func EncodeFullLinkControl(s *FullLinkControl) [96]bit.Bit {
	var data [96]bit.Bit
	switch {
	case s.GroupVoice != nil:
		_pduBits := EncodeFLCGroupVoice(s.GroupVoice)
		copy(data[16:72], _pduBits[:])
	case s.UnitToUnit != nil:
		_pduBits := EncodeFLCUnitToUnit(s.UnitToUnit)
		copy(data[16:72], _pduBits[:])
	case s.GPSInfo != nil:
		_pduBits := EncodeFLCGPSInfo(s.GPSInfo)
		copy(data[16:72], _pduBits[:])
	case s.TalkerAliasHeader != nil:
		_pduBits := EncodeFLCTalkerAliasHeader(s.TalkerAliasHeader)
		copy(data[16:72], _pduBits[:])
	case s.TalkerAliasBlock != nil:
		_pduBits := EncodeFLCTalkerAliasBlock(s.TalkerAliasBlock)
		copy(data[16:72], _pduBits[:])
	case s.TerminatorDataLinkControl != nil:
		_pduBits := EncodeFLCTerminatorDataLinkControl(s.TerminatorDataLinkControl)
		copy(data[16:72], _pduBits[:])
	}
	if s.ProtectFlag {
		data[0] = 1
	}
	copy(data[2:8], bit.BitsFromUint8(uint8(s.FLCO), 6))
	copy(data[8:16], bit.BitsFromUint8(uint8(s.FeatureSetID), 8))
	var _encData [9]byte
	for i := range 9 {
		for j := range 8 {
			_encData[i] <<= 1
			_encData[i] |= byte(data[i*8+j])
		}
	}
	_encoded, _ := reedsolomon.Encode(_encData[:])
	for i := range 12 {
		for j := range 8 {
			data[i*8+j] = bit.Bit((_encoded[i] >> (7 - j)) & 1)
		}
	}
	return data
}

func (s *FullLinkControl) ToString() string {
	_ret := "FullLinkControl{ "
	_ret += fmt.Sprintf("DataType: %s, ProtectFlag: %t, FLCO: %s, FeatureSetID: %s, FEC: {BitsChecked: %d, ErrorsCorrected: %d, Uncorrectable: %t}, ", layer2Elements.DataTypeToName(s.DataType), s.ProtectFlag, enums.FLCOToName(s.FLCO), enums.FeatureSetIDToName(s.FeatureSetID), s.FEC.BitsChecked, s.FEC.ErrorsCorrected, s.FEC.Uncorrectable)
	switch {
	case s.GroupVoice != nil:
		_ret += s.GroupVoice.ToString()
	case s.UnitToUnit != nil:
		_ret += s.UnitToUnit.ToString()
	case s.GPSInfo != nil:
		_ret += s.GPSInfo.ToString()
	case s.TalkerAliasHeader != nil:
		_ret += s.TalkerAliasHeader.ToString()
	case s.TalkerAliasBlock != nil:
		_ret += s.TalkerAliasBlock.ToString()
	case s.TerminatorDataLinkControl != nil:
		_ret += s.TerminatorDataLinkControl.ToString()
	}
	_ret += " }"
	return _ret
}

// DecodeFLCGroupVoice decodes a FLCGroupVoice per ETSI TS 102 361-2 - Table 7.1: Grp_V_Ch_Usr PDU content
func DecodeFLCGroupVoice(data [56]bit.Bit) (FLCGroupVoice, fec.FECResult) {
	var result FLCGroupVoice
	var fecResult fec.FECResult
	var _serviceOptionsBits [8]bit.Bit
	copy(_serviceOptionsBits[:], data[0:8])
	result.ServiceOptions, _ = layer3Elements.DecodeServiceOptions(_serviceOptionsBits)
	result.GroupAddress = bit.BitsToInt(data[:], 8, 24)
	result.SourceAddress = bit.BitsToInt(data[:], 32, 24)
	return result, fecResult
}

// EncodeFLCGroupVoice encodes a FLCGroupVoice per ETSI TS 102 361-2 - Table 7.1: Grp_V_Ch_Usr PDU content
func EncodeFLCGroupVoice(s *FLCGroupVoice) [56]bit.Bit {
	var data [56]bit.Bit
	_serviceOptionsBits := layer3Elements.EncodeServiceOptions(&s.ServiceOptions)
	copy(data[0:8], _serviceOptionsBits[:])
	copy(data[8:32], bit.BitsFromUint32(uint32(s.GroupAddress), 24))
	copy(data[32:56], bit.BitsFromUint32(uint32(s.SourceAddress), 24))
	return data
}

func (s *FLCGroupVoice) ToString() string {
	return fmt.Sprintf("FLCGroupVoice{ ServiceOptions: %s, GroupAddress: %d, SourceAddress: %d }", s.ServiceOptions.ToString(), s.GroupAddress, s.SourceAddress)
}

// DecodeFLCUnitToUnit decodes a FLCUnitToUnit per ETSI TS 102 361-2 - Table 7.2: UU_V_Ch_Usr PDU content
func DecodeFLCUnitToUnit(data [56]bit.Bit) (FLCUnitToUnit, fec.FECResult) {
	var result FLCUnitToUnit
	var fecResult fec.FECResult
	var _serviceOptionsBits [8]bit.Bit
	copy(_serviceOptionsBits[:], data[0:8])
	result.ServiceOptions, _ = layer3Elements.DecodeServiceOptions(_serviceOptionsBits)
	result.TargetAddress = bit.BitsToInt(data[:], 8, 24)
	result.SourceAddress = bit.BitsToInt(data[:], 32, 24)
	return result, fecResult
}

// EncodeFLCUnitToUnit encodes a FLCUnitToUnit per ETSI TS 102 361-2 - Table 7.2: UU_V_Ch_Usr PDU content
func EncodeFLCUnitToUnit(s *FLCUnitToUnit) [56]bit.Bit {
	var data [56]bit.Bit
	_serviceOptionsBits := layer3Elements.EncodeServiceOptions(&s.ServiceOptions)
	copy(data[0:8], _serviceOptionsBits[:])
	copy(data[8:32], bit.BitsFromUint32(uint32(s.TargetAddress), 24))
	copy(data[32:56], bit.BitsFromUint32(uint32(s.SourceAddress), 24))
	return data
}

func (s *FLCUnitToUnit) ToString() string {
	return fmt.Sprintf("FLCUnitToUnit{ ServiceOptions: %s, TargetAddress: %d, SourceAddress: %d }", s.ServiceOptions.ToString(), s.TargetAddress, s.SourceAddress)
}

// DecodeFLCGPSInfo decodes a FLCGPSInfo per ETSI TS 102 361-2 - Table 7.3: GPS Info PDU content
func DecodeFLCGPSInfo(data [56]bit.Bit) (FLCGPSInfo, fec.FECResult) {
	var result FLCGPSInfo
	var fecResult fec.FECResult
	result.PositionError = layer3Elements.PositionError(bit.BitsToUint8(data[4:7], 0, 3))
	result.Longitude = float32(bit.BitsToInt(data[:], 7, 25)) * float32(360.0/math.Pow(2.0, 25.0))
	result.Latitude = float32(bit.BitsToInt(data[:], 32, 24)) * float32(180.0/math.Pow(2.0, 24.0))
	return result, fecResult
}

// EncodeFLCGPSInfo encodes a FLCGPSInfo per ETSI TS 102 361-2 - Table 7.3: GPS Info PDU content
func EncodeFLCGPSInfo(s *FLCGPSInfo) [56]bit.Bit {
	var data [56]bit.Bit
	copy(data[4:7], bit.BitsFromUint8(uint8(s.PositionError), 3))
	copy(data[7:32], bit.BitsFromUint32(uint32(s.Longitude/float32(360.0/math.Pow(2.0, 25.0))), 25))
	copy(data[32:56], bit.BitsFromUint32(uint32(s.Latitude/float32(180.0/math.Pow(2.0, 24.0))), 24))
	return data
}

func (s *FLCGPSInfo) ToString() string {
	return fmt.Sprintf("FLCGPSInfo{ PositionError: %s, Longitude: %f, Latitude: %f }", layer3Elements.PositionErrorToName(s.PositionError), s.Longitude, s.Latitude)
}

// DecodeFLCTalkerAliasHeader decodes a FLCTalkerAliasHeader per ETSI TS 102 361-2 - Table 7.4: Talker Alias Header Info PDU content
func DecodeFLCTalkerAliasHeader(data [56]bit.Bit) (FLCTalkerAliasHeader, fec.FECResult) {
	var result FLCTalkerAliasHeader
	var fecResult fec.FECResult
	result.TalkerAliasDataFormat = layer3Elements.TalkerAliasDataFormat(bit.BitsToUint8(data[0:2], 0, 2))
	result.TalkerAliasDataLength = bit.BitsToInt(data[:], 2, 6)
	result.TalkerAliasDataMSB = bit.BitsToBool(data[:], 7)
	copy(result.TalkerAliasData[:], data[8:56])
	return result, fecResult
}

// EncodeFLCTalkerAliasHeader encodes a FLCTalkerAliasHeader per ETSI TS 102 361-2 - Table 7.4: Talker Alias Header Info PDU content
func EncodeFLCTalkerAliasHeader(s *FLCTalkerAliasHeader) [56]bit.Bit {
	var data [56]bit.Bit
	copy(data[0:2], bit.BitsFromUint8(uint8(s.TalkerAliasDataFormat), 2))
	copy(data[2:8], bit.BitsFromUint32(uint32(s.TalkerAliasDataLength), 6))
	if s.TalkerAliasDataMSB {
		data[7] = 1
	}
	copy(data[8:56], s.TalkerAliasData[:])
	return data
}

func (s *FLCTalkerAliasHeader) ToString() string {
	return fmt.Sprintf("FLCTalkerAliasHeader{ TalkerAliasDataFormat: %s, TalkerAliasDataLength: %d, TalkerAliasDataMSB: %t, TalkerAliasData: %v }", layer3Elements.TalkerAliasDataFormatToName(s.TalkerAliasDataFormat), s.TalkerAliasDataLength, s.TalkerAliasDataMSB, s.TalkerAliasData)
}

// DecodeFLCTalkerAliasBlock decodes a FLCTalkerAliasBlock per ETSI TS 102 361-2 - Table 7.5: Talker Alias Blk PDU content
func DecodeFLCTalkerAliasBlock(data [56]bit.Bit) (FLCTalkerAliasBlock, fec.FECResult) {
	var result FLCTalkerAliasBlock
	var fecResult fec.FECResult
	copy(result.TalkerAliasData[:], data[0:56])
	return result, fecResult
}

// EncodeFLCTalkerAliasBlock encodes a FLCTalkerAliasBlock per ETSI TS 102 361-2 - Table 7.5: Talker Alias Blk PDU content
func EncodeFLCTalkerAliasBlock(s *FLCTalkerAliasBlock) [56]bit.Bit {
	var data [56]bit.Bit
	copy(data[0:56], s.TalkerAliasData[:])
	return data
}

func (s *FLCTalkerAliasBlock) ToString() string {
	return fmt.Sprintf("FLCTalkerAliasBlock{ TalkerAliasData: %v }", s.TalkerAliasData)
}

// DecodeFLCTerminatorDataLinkControl decodes a FLCTerminatorDataLinkControl per ETSI TS 102 361-3 - Table 7.1: Terminator Data Link Control PDU content
func DecodeFLCTerminatorDataLinkControl(data [56]bit.Bit) (FLCTerminatorDataLinkControl, fec.FECResult) {
	var result FLCTerminatorDataLinkControl
	var fecResult fec.FECResult
	result.LLIDDestination = bit.BitsToInt(data[:], 0, 24)
	result.LLIDSource = bit.BitsToInt(data[:], 24, 24)
	result.GroupOrIndividual = bit.BitsToBool(data[:], 48)
	result.ResponseRequested = bit.BitsToBool(data[:], 49)
	result.FullMessageFlag = bit.BitsToBool(data[:], 50)
	result.ReSynchronizeFlag = bit.BitsToBool(data[:], 52)
	result.SendSequenceNumber = bit.BitsToUint8(data[:], 53, 3)
	return result, fecResult
}

// EncodeFLCTerminatorDataLinkControl encodes a FLCTerminatorDataLinkControl per ETSI TS 102 361-3 - Table 7.1: Terminator Data Link Control PDU content
func EncodeFLCTerminatorDataLinkControl(s *FLCTerminatorDataLinkControl) [56]bit.Bit {
	var data [56]bit.Bit
	copy(data[0:24], bit.BitsFromUint32(uint32(s.LLIDDestination), 24))
	copy(data[24:48], bit.BitsFromUint32(uint32(s.LLIDSource), 24))
	if s.GroupOrIndividual {
		data[48] = 1
	}
	if s.ResponseRequested {
		data[49] = 1
	}
	if s.FullMessageFlag {
		data[50] = 1
	}
	if s.ReSynchronizeFlag {
		data[52] = 1
	}
	copy(data[53:56], bit.BitsFromUint8(s.SendSequenceNumber, 3))
	return data
}

func (s *FLCTerminatorDataLinkControl) ToString() string {
	return fmt.Sprintf("FLCTerminatorDataLinkControl{ LLIDDestination: %d, LLIDSource: %d, GroupOrIndividual: %t, ResponseRequested: %t, FullMessageFlag: %t, ReSynchronizeFlag: %t, SendSequenceNumber: %d }", s.LLIDDestination, s.LLIDSource, s.GroupOrIndividual, s.ResponseRequested, s.FullMessageFlag, s.ReSynchronizeFlag, s.SendSequenceNumber)
}
