/*
Code generated by dmrgen.

ETSI TS 102 361-1 - 9.1.7 Rate 3/4 data

DO NOT EDIT.
*/

package pdu

import (
	"fmt"
	bit "github.com/USA-RedDragon/dmrgo/v2/bit"
	fec "github.com/USA-RedDragon/dmrgo/v2/fec"
	layer2Elements "github.com/USA-RedDragon/dmrgo/v2/layer2/elements"
)

// DecodeRate34Data decodes a Rate34Data per ETSI TS 102 361-1 - 9.1.7 Rate 3/4 data
func DecodeRate34Data(data [96]bit.Bit) (Rate34Data, fec.FECResult) {
	var result Rate34Data
	var fecResult fec.FECResult
	copy(result.Data[:], bit.PackBits(data[0:96]))
	return result, fecResult
}

// EncodeRate34Data encodes a Rate34Data per ETSI TS 102 361-1 - 9.1.7 Rate 3/4 data
func EncodeRate34Data(s *Rate34Data) [96]bit.Bit {
	var data [96]bit.Bit
	copy(data[0:96], bit.UnpackBits(s.Data[:]))
	return data
}

func (s *Rate34Data) ToString() string {
	return fmt.Sprintf("Rate34Data{ DataType: %s, Data: %v }", layer2Elements.DataTypeToName(s.DataType), s.Data)
}
