/*
Code generated by dmrgen.

ETSI TS 102 361-1 V2.5.1 (2017-10) - 9.1.7 Rate 1/2 data

DO NOT EDIT.
*/

package pdu

import (
	"fmt"
	bit "github.com/USA-RedDragon/dmrgo/v2/bit"
	fec "github.com/USA-RedDragon/dmrgo/v2/fec"
	layer2Elements "github.com/USA-RedDragon/dmrgo/v2/layer2/elements"
)

// DecodeRate12Data decodes a Rate12Data per ETSI TS 102 361-1 V2.5.1 (2017-10) - 9.1.7 Rate 1/2 data
func DecodeRate12Data(data [96]bit.Bit) (Rate12Data, fec.FECResult) {
	var result Rate12Data
	var fecResult fec.FECResult
	copy(result.Data[:], bit.PackBits(data[0:96]))
	return result, fecResult
}

// EncodeRate12Data encodes a Rate12Data per ETSI TS 102 361-1 V2.5.1 (2017-10) - 9.1.7 Rate 1/2 data
func EncodeRate12Data(s *Rate12Data) [96]bit.Bit {
	var data [96]bit.Bit
	copy(data[0:96], bit.UnpackBits(s.Data[:]))
	return data
}

func (s *Rate12Data) ToString() string {
	return fmt.Sprintf("Rate12Data{ DataType: %s, Data: %v }", layer2Elements.DataTypeToName(s.DataType), s.Data)
}
