/*
Code generated by dmrgen.

ETSI TS 102 361-2 - 7.1.1 Short LC Null Message PDU
ETSI TS 102 361-2 - 7.1.2 Activity Update PDU
ETSI TS 102 361-1 - 9.1.7 Short Link Control (SHORT_LC) PDU

DO NOT EDIT.
*/

package pdu

import (
	"fmt"
	bit "github.com/USA-RedDragon/dmrgo/v2/bit"
	crc "github.com/USA-RedDragon/dmrgo/v2/crc"
	enums "github.com/USA-RedDragon/dmrgo/v2/enums"
	fec "github.com/USA-RedDragon/dmrgo/v2/fec"
	layer2Elements "github.com/USA-RedDragon/dmrgo/v2/layer2/elements"
)

// DecodeShortLCNullMessage decodes a ShortLCNullMessage per ETSI TS 102 361-2 - 7.1.1 Short LC Null Message PDU
func DecodeShortLCNullMessage(data [24]bit.Bit) (ShortLCNullMessage, fec.FECResult) {
	var result ShortLCNullMessage
	var fecResult fec.FECResult
	copy(result.Reserved[:], data[0:24])
	return result, fecResult
}

// EncodeShortLCNullMessage encodes a ShortLCNullMessage per ETSI TS 102 361-2 - 7.1.1 Short LC Null Message PDU
func EncodeShortLCNullMessage(s *ShortLCNullMessage) [24]bit.Bit {
	var data [24]bit.Bit
	copy(data[0:24], s.Reserved[:])
	return data
}

func (s *ShortLCNullMessage) ToString() string {
	return fmt.Sprintf("ShortLCNullMessage{ Reserved: %v }", s.Reserved)
}

// DecodeShortLCActivityUpdate decodes a ShortLCActivityUpdate per ETSI TS 102 361-2 - 7.1.2 Activity Update PDU
func DecodeShortLCActivityUpdate(data [24]bit.Bit) (ShortLCActivityUpdate, fec.FECResult) {
	var result ShortLCActivityUpdate
	var fecResult fec.FECResult
	result.TS1ActivityID = enums.ActivityIDFromInt(bit.BitsToInt(data[:], 0, 4))
	result.TS2ActivityID = enums.ActivityIDFromInt(bit.BitsToInt(data[:], 4, 4))
	result.HashTS1 = bit.BitsToUint8(data[:], 8, 8)
	result.HashTS2 = bit.BitsToUint8(data[:], 16, 8)
	return result, fecResult
}

// EncodeShortLCActivityUpdate encodes a ShortLCActivityUpdate per ETSI TS 102 361-2 - 7.1.2 Activity Update PDU
func EncodeShortLCActivityUpdate(s *ShortLCActivityUpdate) [24]bit.Bit {
	var data [24]bit.Bit
	copy(data[0:4], bit.BitsFromUint8(uint8(s.TS1ActivityID), 4))
	copy(data[4:8], bit.BitsFromUint8(uint8(s.TS2ActivityID), 4))
	copy(data[8:16], bit.BitsFromUint8(uint8(s.HashTS1), 8))
	copy(data[16:24], bit.BitsFromUint8(uint8(s.HashTS2), 8))
	return data
}

func (s *ShortLCActivityUpdate) ToString() string {
	return fmt.Sprintf("ShortLCActivityUpdate{ TS1ActivityID: %s, TS2ActivityID: %s, HashTS1: %d, HashTS2: %d }", enums.ActivityIDToName(s.TS1ActivityID), enums.ActivityIDToName(s.TS2ActivityID), s.HashTS1, s.HashTS2)
}

// DecodeShortLC decodes a ShortLC per ETSI TS 102 361-1 - 9.1.7 Short Link Control (SHORT_LC) PDU
func DecodeShortLC(data [36]bit.Bit) (ShortLC, fec.FECResult) {
	var result ShortLC
	var fecResult fec.FECResult
	fecResult.BitsChecked = 36
	if !crc.CheckCRC8(data[:]) {
		fecResult.Uncorrectable = true
	}
	result.FEC = fecResult
	var _crcVal uint8
	for i := range 8 {
		_crcVal <<= 1
		_crcVal |= uint8(data[28+i])
	}
	result.crc = _crcVal
	result.SLCO = enums.SLCOFromInt(bit.BitsToInt(data[:], 0, 4))
	var _dispatchBits [24]bit.Bit
	copy(_dispatchBits[:], data[4:28])
	switch result.SLCO {
	case enums.SLCONullMessage:
		_decoded, _ := DecodeShortLCNullMessage(_dispatchBits)
		result.NullMessage = &_decoded
	case enums.SLCOActivityUpdate:
		_decoded, _ := DecodeShortLCActivityUpdate(_dispatchBits)
		result.ActivityUpdate = &_decoded
	}
	return result, fecResult
}

// EncodeShortLC encodes a ShortLC per ETSI TS 102 361-1 - 9.1.7 Short Link Control (SHORT_LC) PDU
func EncodeShortLC(s *ShortLC) [36]bit.Bit {
	var data [36]bit.Bit
	copy(data[0:4], bit.BitsFromUint8(uint8(s.SLCO), 4))
	switch {
	case s.NullMessage != nil:
		_pduBits := EncodeShortLCNullMessage(s.NullMessage)
		copy(data[4:28], _pduBits[:])
	case s.ActivityUpdate != nil:
		_pduBits := EncodeShortLCActivityUpdate(s.ActivityUpdate)
		copy(data[4:28], _pduBits[:])
	}
	_crcVal := crc.CalculateCRC8(data[:28])
	for j := range 8 {
		data[28+j] = bit.Bit((_crcVal >> (7 - j)) & 1)
	}
	return data
}

func (s *ShortLC) ToString() string {
	_ret := "ShortLC{ "
	_ret += fmt.Sprintf("DataType: %s, SLCO: %s, FEC: {BitsChecked: %d, ErrorsCorrected: %d, Uncorrectable: %t}, ", layer2Elements.DataTypeToName(s.DataType), enums.SLCOToName(s.SLCO), s.FEC.BitsChecked, s.FEC.ErrorsCorrected, s.FEC.Uncorrectable)
	switch {
	case s.NullMessage != nil:
		_ret += s.NullMessage.ToString()
	case s.ActivityUpdate != nil:
		_ret += s.ActivityUpdate.ToString()
	}
	_ret += " }"
	return _ret
}
