/*
Code generated by dmrgen.

ETSI TS 102 361-3 - Table 7.14: UDP/IPv4 Compressed Header

DO NOT EDIT.
*/

package pdu

import (
	"fmt"
	bit "github.com/USA-RedDragon/dmrgo/v2/bit"
	fec "github.com/USA-RedDragon/dmrgo/v2/fec"
)

// DecodeUDPIPv4CompressedHeader decodes a UDPIPv4CompressedHeader per ETSI TS 102 361-3 - Table 7.14: UDP/IPv4 Compressed Header
func DecodeUDPIPv4CompressedHeader(data [72]bit.Bit) (UDPIPv4CompressedHeader, fec.FECResult) {
	var result UDPIPv4CompressedHeader
	var fecResult fec.FECResult
	result.IPv4Identification = bit.BitsToUint16(data[:], 0, 16)
	result.SAID = bit.BitsToUint8(data[:], 16, 4)
	result.DAID = bit.BitsToUint8(data[:], 20, 4)
	var _tmpHeaderCompressionOpcode uint8
	_tmpHeaderCompressionOpcode = bit.BitsToUint8(data[:], 24, 1)
	_tmpHeaderCompressionOpcode <<= 1
	_tmpHeaderCompressionOpcode |= bit.BitsToUint8(data[:], 32, 1)
	result.HeaderCompressionOpcode = _tmpHeaderCompressionOpcode
	result.SPID = bit.BitsToUint8(data[:], 25, 7)
	result.DPID = bit.BitsToUint8(data[:], 33, 7)
	result.ExtendedHeader1 = bit.BitsToUint16(data[:], 40, 16)
	result.ExtendedHeader2 = bit.BitsToUint16(data[:], 56, 16)
	return result, fecResult
}

// EncodeUDPIPv4CompressedHeader encodes a UDPIPv4CompressedHeader per ETSI TS 102 361-3 - Table 7.14: UDP/IPv4 Compressed Header
func EncodeUDPIPv4CompressedHeader(s *UDPIPv4CompressedHeader) [72]bit.Bit {
	var data [72]bit.Bit
	copy(data[0:16], bit.BitsFromUint16(s.IPv4Identification, 16))
	copy(data[16:20], bit.BitsFromUint8(s.SAID, 4))
	copy(data[20:24], bit.BitsFromUint8(s.DAID, 4))
	copy(data[24:25], bit.BitsFromUint8((uint8(s.HeaderCompressionOpcode))>>1, 1))
	copy(data[32:33], bit.BitsFromUint8(s.HeaderCompressionOpcode, 1))
	copy(data[25:32], bit.BitsFromUint8(s.SPID, 7))
	copy(data[33:40], bit.BitsFromUint8(s.DPID, 7))
	copy(data[40:56], bit.BitsFromUint16(s.ExtendedHeader1, 16))
	copy(data[56:72], bit.BitsFromUint16(s.ExtendedHeader2, 16))
	return data
}

func (s *UDPIPv4CompressedHeader) ToString() string {
	return fmt.Sprintf("UDPIPv4CompressedHeader{ IPv4Identification: %d, SAID: %d, DAID: %d, HeaderCompressionOpcode: %d, SPID: %d, DPID: %d, ExtendedHeader1: %d, ExtendedHeader2: %d }", s.IPv4Identification, s.SAID, s.DAID, s.HeaderCompressionOpcode, s.SPID, s.DPID, s.ExtendedHeader1, s.ExtendedHeader2)
}
