/*
Code generated by dmrgen.

ETSI TS 102 361-1 - 7.1 Voice channel coding

DO NOT EDIT.
*/

package pdu

import (
	bit "github.com/USA-RedDragon/dmrgo/v2/bit"
	fec "github.com/USA-RedDragon/dmrgo/v2/fec"
	vocoder "github.com/USA-RedDragon/dmrgo/v2/vocoder"
)

// DecodeVocoder decodes a Vocoder per ETSI TS 102 361-1 - 7.1 Voice channel coding
func DecodeVocoder(data [216]bit.Bit) (Vocoder, fec.FECResult) {
	var result Vocoder
	var fecResult fec.FECResult
	for _i := 0; _i < 3; _i++ {
		var _elemBits [72]bit.Bit
		copy(_elemBits[:], data[0+_i*72:0+_i*72+72])
		result.Frames[_i], _ = vocoder.DecodeVocoderFrame(_elemBits)
	}
	return result, fecResult
}

// EncodeVocoder encodes a Vocoder per ETSI TS 102 361-1 - 7.1 Voice channel coding
func EncodeVocoder(s *Vocoder) [216]bit.Bit {
	var data [216]bit.Bit
	for _i := 0; _i < 3; _i++ {
		_elemBits := vocoder.EncodeVocoderFrame(&s.Frames[_i])
		copy(data[0+_i*72:0+_i*72+72], _elemBits[:])
	}
	return data
}

func (s *Vocoder) ToString() string {
	_ret := "Vocoder{ "
	_ret += "Frames: ["
	for _i := range s.Frames {
		if _i > 0 {
			_ret += ", "
		}
		_ret += s.Frames[_i].ToString()
	}
	_ret += "]"
	_ret += " }"
	return _ret
}
