/*
Code generated by dmrgen.

ETSI TS 102 361-4 — §7.2.42, Table 7.103

DO NOT EDIT.
*/

package elements

import (
	"fmt"
	bit "github.com/USA-RedDragon/dmrgo/v2/bit"
	fec "github.com/USA-RedDragon/dmrgo/v2/fec"
)

// DecodeCdefParms decodes a CdefParms per ETSI TS 102 361-4 — §7.2.42, Table 7.103
func DecodeCdefParms(data [58]bit.Bit) (CdefParms, fec.FECResult) {
	var result CdefParms
	var fecResult fec.FECResult
	result.Channel = bit.BitsToUint16(data[:], 0, 12)
	result.TXMHz = bit.BitsToUint16(data[:], 12, 10)
	result.TXKHz = bit.BitsToUint16(data[:], 22, 13)
	result.RXMHz = bit.BitsToUint16(data[:], 35, 10)
	result.RXKHz = bit.BitsToUint16(data[:], 45, 13)
	return result, fecResult
}

// EncodeCdefParms encodes a CdefParms per ETSI TS 102 361-4 — §7.2.42, Table 7.103
func EncodeCdefParms(s *CdefParms) [58]bit.Bit {
	var data [58]bit.Bit
	copy(data[0:12], bit.BitsFromUint16(s.Channel, 12))
	copy(data[12:22], bit.BitsFromUint16(s.TXMHz, 10))
	copy(data[22:35], bit.BitsFromUint16(s.TXKHz, 13))
	copy(data[35:45], bit.BitsFromUint16(s.RXMHz, 10))
	copy(data[45:58], bit.BitsFromUint16(s.RXKHz, 13))
	return data
}

func (s *CdefParms) ToString() string {
	return fmt.Sprintf("CdefParms{ Channel: %d, TXMHz: %d, TXKHz: %d, RXMHz: %d, RXKHz: %d }", s.Channel, s.TXMHz, s.TXKHz, s.RXMHz, s.RXKHz)
}
