/*
Code generated by dmrgen.

ETSI TS 102 361-2 V2.4.1 (2017-10) - 7.2.1  Service Options

DO NOT EDIT.
*/

package elements

import (
	"fmt"
	bit "github.com/USA-RedDragon/dmrgo/v2/bit"
	fec "github.com/USA-RedDragon/dmrgo/v2/fec"
)

// DecodeServiceOptions decodes a ServiceOptions per ETSI TS 102 361-2 V2.4.1 (2017-10) - 7.2.1  Service Options
func DecodeServiceOptions(data [8]bit.Bit) (ServiceOptions, fec.FECResult) {
	var result ServiceOptions
	var fecResult fec.FECResult
	result.IsEmergency = bit.BitsToBool(data[:], 0)
	result.IsPrivacy = bit.BitsToBool(data[:], 1)
	copy(result.Reserved[:], data[2:4])
	result.IsBroadcast = bit.BitsToBool(data[:], 4)
	result.IsOpenVoiceCallMode = bit.BitsToBool(data[:], 5)
	result.PriorityLevel = bit.BitsToUint8(data[:], 6, 2)
	return result, fecResult
}

// EncodeServiceOptions encodes a ServiceOptions per ETSI TS 102 361-2 V2.4.1 (2017-10) - 7.2.1  Service Options
func EncodeServiceOptions(s *ServiceOptions) [8]bit.Bit {
	var data [8]bit.Bit
	if s.IsEmergency {
		data[0] = 1
	}
	if s.IsPrivacy {
		data[1] = 1
	}
	copy(data[2:4], s.Reserved[:])
	if s.IsBroadcast {
		data[4] = 1
	}
	if s.IsOpenVoiceCallMode {
		data[5] = 1
	}
	copy(data[6:8], bit.BitsFromUint8(s.PriorityLevel, 2))
	return data
}

func (s *ServiceOptions) ToString() string {
	return fmt.Sprintf("ServiceOptions{ IsEmergency: %t, IsPrivacy: %t, Reserved: %v, IsBroadcast: %t, IsOpenVoiceCallMode: %t, PriorityLevel: %d }", s.IsEmergency, s.IsPrivacy, s.Reserved, s.IsBroadcast, s.IsOpenVoiceCallMode, s.PriorityLevel)
}
