name: Spec Check

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  spec-check:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Set up Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: go.mod

      - run: go generate ./...

      - name: Spec check README
        run: |
          cd cmd/speccheck
          env CGO_ENABLED=0 go run . -update-readme || true

      - uses: stefanzweifel/git-auto-commit-action@4a55954c782fc1ea30b9056cd3e7a2b40ca8887d # v7.2.0
        with:
          commit_message: "Update ETSI TS 102 361 specification coverage"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "41898282+github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"

      - name: Spec check validation
        run: |
          cd cmd/speccheck
          env CGO_ENABLED=0 go run .
