name: Tests

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read       # Required for actions/checkout
  checks:   write      # Required for GitHub Checks API

jobs:
  benchmark-tests:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Set up Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: go.mod

      - run: go generate ./...

      - run: CGO_ENABLED=0 go test -C v2 -run ^$ -benchmem -bench=. ./...

  race-tests:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Set up Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: go.mod

      - run: go generate ./...

      - name: Race tests
        run: go test -C v2 ./... -race

  unit-tests:
    uses: ./.github/workflows/unit-test.yaml
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  unit-tests-coverage:
    uses: ./.github/workflows/unit-test.yaml
    with:
      coverage: true
    secrets:
      codecov_token: ${{ secrets.CODECOV_TOKEN }}
      token: ${{ secrets.GITHUB_TOKEN }}
